package controller.simulating;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import main.MainFields3;
import javafx.event.ActionEvent;

public class MenuController {
	@FXML
	private Button btn1;
	@FXML
	private Button btn2;
	@FXML
	private Button btn3;
	@FXML
	private Button btnQuit;

	// Event Listener on Button[#btn1].onAction
	@FXML
	public void btnClick(ActionEvent event) {
		// TODO Autogenerated
Button src = (Button) event.getSource();
		
		if(src == btn1) {
			MainFields3.setSamplingTechnique("Simple Random Sampling");
		} else if(src == btn2) {
			MainFields3.setSamplingTechnique("Systematic Sampling");
		} else if(src == btn3) {
			MainFields3.setSamplingTechnique("Stratified Sampling");
		} else {
			System.exit(0);
		}
	}
}
