package controller.simulating;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.stage.Modality;
import javafx.stage.Stage;
import main.MainFields3;

import java.io.IOException;

import javafx.event.ActionEvent;

public class MenuController {
	@FXML
	private Button btn1;
	@FXML
	private Button btn2;
	@FXML
	private Button btn3;
	@FXML
	private Button btnQuit;

	// Event Listener on Button[#btn1].onAction
	@FXML
	public void btnClick(ActionEvent event) throws IOException {
		// TODO Autogenerated
Button src = (Button) event.getSource();
		
		if(src == btn1) {
			MainFields3.setSamplingTechnique("Simple Random Sampling");
		} else if(src == btn2) {
			MainFields3.setSamplingTechnique("Systematic Sampling");
		} else if(src == btn3) {
			MainFields3.setSamplingTechnique("Stratified Sampling");
		} else {
			System.exit(0);
		}
		Stage stage = (Stage) btn1.getScene().getWindow();
		Parent root = FXMLLoader.load(getClass().getResource("/view/simulating/PopulationInput.fxml"));
		Scene scene = new Scene(root);
		scene.getStylesheets().add("/theme/bloodcrimson.css");
		stage.setTitle("Input Population");
		stage.setScene(scene);
		stage.show();
	}
}
